Activity Indicator When logging in
nordenmark/yaniv pull request #8
Opened 2019-10-22 15:35 UTC by ThalapathySiva

Activity Indicator When logging in

Issue : https://github.com/nordenmark/yaniv/issues/7

2019-10-28 09:43 UTC, damoonrashidi requested changes
Great job, just two small comments! Thanks for the PR

2019-10-28 09:43 UTC, damoonrashidi commented on lib/screens/login.screen.dart
> +      print("fsf");
Left over debugging message?

2019-10-28 09:43 UTC, damoonrashidi commented on lib/screens/login.screen.dart
> +            ? Center(child: CupertinoActivityIndicator())
Preferably this should be a`CircularProgressIndicator` or similar instead of the Cupertino one.

2019-10-29 04:02 UTC, ThalapathySiva commented
Now changed Go ahead!

2019-10-29 11:50 UTC, damoonrashidi approved these changes
Thanks! looks good to me!

2019-10-29 11:50 UTC, merged